/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocesRouteImport } from './routes/doces'
import { Route as EnjoeiRouteImport } from './routes/enjoei'
import { Route as ShopeeRouteImport } from './routes/shopee'
import { Route as VendasRouteImport } from './routes/vendas'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocesRoute = DocesRouteImport.update({
  id: '/doces',
  path: '/doces',
  getParentRoute: () => rootRouteImport,
} as any)
const EnjoeiRoute = EnjoeiRouteImport.update({
  id: '/enjoei',
  path: '/enjoei',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopeeRoute = ShopeeRouteImport.update({
  id: '/shopee',
  path: '/shopee',
  getParentRoute: () => rootRouteImport,
} as any)
const VendasRoute = VendasRouteImport.update({
  id: '/vendas',
  path: '/vendas',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/doces': typeof DocesRoute
  '/enjoei': typeof EnjoeiRoute
  '/shopee': typeof ShopeeRoute
  '/vendas': typeof VendasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/doces': typeof DocesRoute
  '/enjoei': typeof EnjoeiRoute
  '/shopee': typeof ShopeeRoute
  '/vendas': typeof VendasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/doces': typeof DocesRoute
  '/enjoei': typeof EnjoeiRoute
  '/shopee': typeof ShopeeRoute
  '/vendas': typeof VendasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/doces' | '/enjoei' | '/shopee' | '/vendas'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/doces' | '/enjoei' | '/shopee' | '/vendas'
  id: '__root__' | '/' | '/doces' | '/enjoei' | '/shopee' | '/vendas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DocesRoute: typeof DocesRoute
  EnjoeiRoute: typeof EnjoeiRoute
  ShopeeRoute: typeof ShopeeRoute
  VendasRoute: typeof VendasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doces': {
      id: '/doces'
      path: '/doces'
      fullPath: '/doces'
      preLoaderRoute: typeof DocesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enjoei': {
      id: '/enjoei'
      path: '/enjoei'
      fullPath: '/enjoei'
      preLoaderRoute: typeof EnjoeiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shopee': {
      id: '/shopee'
      path: '/shopee'
      fullPath: '/shopee'
      preLoaderRoute: typeof ShopeeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendas': {
      id: '/vendas'
      path: '/vendas'
      fullPath: '/vendas'
      preLoaderRoute: typeof VendasRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DocesRoute: DocesRoute,
  EnjoeiRoute: EnjoeiRoute,
  ShopeeRoute: ShopeeRoute,
  VendasRoute: VendasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
