/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EnjoeiRouteImport } from './routes/enjoei'
import { Route as ShopeeRouteImport } from './routes/shopee'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EnjoeiRoute = EnjoeiRouteImport.update({
  id: '/enjoei',
  path: '/enjoei',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopeeRoute = ShopeeRouteImport.update({
  id: '/shopee',
  path: '/shopee',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/enjoei': typeof EnjoeiRoute
  '/shopee': typeof ShopeeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/enjoei': typeof EnjoeiRoute
  '/shopee': typeof ShopeeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/enjoei': typeof EnjoeiRoute
  '/shopee': typeof ShopeeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/enjoei' | '/shopee'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/enjoei' | '/shopee'
  id: '__root__' | '/' | '/enjoei' | '/shopee'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EnjoeiRoute: typeof EnjoeiRoute
  ShopeeRoute: typeof ShopeeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enjoei': {
      id: '/enjoei'
      path: '/enjoei'
      fullPath: '/enjoei'
      preLoaderRoute: typeof EnjoeiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shopee': {
      id: '/shopee'
      path: '/shopee'
      fullPath: '/shopee'
      preLoaderRoute: typeof ShopeeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EnjoeiRoute: EnjoeiRoute,
  ShopeeRoute: ShopeeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
